name: Generate Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2      
      
      - name: Generate Snake Animation
        uses: platane/snk@v1.0.0
        with:
          github_user_name: wahajurehmank
          svg_out_path: dist/snake.svg

      - name: Commit and push generated SVG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/snake.svg
          git commit -m "Update snake animation" || true
          git push
